apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartneighbor
  labels:
    app.kubernetes.io/name: smartneighbor
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: smartneighbor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartneighbor
                port:
                  number: 80
