apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smartneighbor
  labels:
    app.kubernetes.io/name: smartneighbor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smartneighbor
      app.kubernetes.io/component: app
